-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 15:23:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GestionEscolar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GestionEscolar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GestionEscolar` DEFAULT CHARACTER SET utf8 ;
USE `GestionEscolar` ;

-- -----------------------------------------------------
-- Table `GestionEscolar`.`Escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`Escuela` (
  `IdEscuela` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`IdEscuela`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionEscolar`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`Personal` (
  `IdPersonal` INT NOT NULL,
  `IdEscuela` INT NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `ApellidoPaterno` VARCHAR(60) NOT NULL,
  `ApellidoMaterno` VARCHAR(60) NOT NULL,
  `Genero` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `RFC` VARCHAR(45) NOT NULL,
  `CURP` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Colonia` VARCHAR(45) NOT NULL,
  `CodigoPostal` INT NOT NULL,
  `CredencialElector` BLOB NOT NULL,
  `PreparacionAcademica` VARCHAR(45) NOT NULL,
  `ComprobanteEstudios` BLOB NOT NULL,
  `ArticuloExistente` VARCHAR(45) NOT NULL,
  `NombreArticulo` VARCHAR(45) NULL,
  `DescripcionArticulo` LONGTEXT NULL,
  `ComprobanteArticulo` BLOB NULL,
  `Turno` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(60) NOT NULL,
  `CargoAux` VARCHAR(60) NULL,
  `OtraEscuela` VARCHAR(10) NOT NULL,
  `IdOtraEscuela` VARCHAR(30) NULL,
  `Discapacidad` VARCHAR(10) NOT NULL,
  `DescripcionDiscapacidad` LONGTEXT NULL,
  `ComprobanteDiscapacidad` BLOB NULL,
  `CorreoElectronico` VARCHAR(45) NOT NULL,
  `ImpartirClases` VARCHAR(10) NOT NULL,
  `MateriaImpartida` VARCHAR(45) NULL,
  PRIMARY KEY (`IdPersonal`),
  INDEX `IdEscuela_idx` (`IdEscuela` ASC) VISIBLE,
  CONSTRAINT `IdEscuela`
    FOREIGN KEY (`IdEscuela`)
    REFERENCES `GestionEscolar`.`Escuela` (`IdEscuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `GestionEscolar`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`Materia` (
  `IdMateria` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Materiacol` VARCHAR(45) NULL,
  PRIMARY KEY (`IdMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionEscolar`.`PersonalMateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`PersonalMateria` (
  `Personal_IdPersonal` INT NOT NULL,
  `Materia_IdMateria` INT NOT NULL,
  PRIMARY KEY (`Personal_IdPersonal`, `Materia_IdMateria`),
  INDEX `fk_Personal_has_Materia_Materia1_idx` (`Materia_IdMateria` ASC) VISIBLE,
  INDEX `fk_Personal_has_Materia_Personal1_idx` (`Personal_IdPersonal` ASC) VISIBLE,
  CONSTRAINT `fk_Personal_has_Materia_Personal1`
    FOREIGN KEY (`Personal_IdPersonal`)
    REFERENCES `GestionEscolar`.`Personal` (`IdPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personal_has_Materia_Materia1`
    FOREIGN KEY (`Materia_IdMateria`)
    REFERENCES `GestionEscolar`.`Materia` (`IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionEscolar`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`Alumno` (
  `IdAlumno` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoPaterno` VARCHAR(45) NOT NULL,
  `ApellidoMaterno` VARCHAR(45) NOT NULL,
  `CURP` VARCHAR(45) NOT NULL,
  `FechaNacimiento` DATETIME(20) NULL,
  `Peso` DOUBLE NOT NULL,
  `Altura` DOUBLE NOT NULL,
  `TallaCamisa` VARCHAR(45) NOT NULL,
  `TallaPantalonFalda` VARCHAR(45) NOT NULL,
  `TipoDeSangre` VARCHAR(10) NOT NULL,
  `Mano` VARCHAR(45) NOT NULL,
  `Discapacidad` VARCHAR(45) NULL,
  `SeguimientoDiscapacidad` VARCHAR(10) NULL,
  `EnfermedadAlergia` VARCHAR(45) NULL,
  `ActaDeNacimiento` BLOB NOT NULL,
  `CURPdoc` BLOB NOT NULL,
  `AcreditacionDiscapacidad` BLOB NULL,
  `AcreditacionEnfermedad` BLOB NULL,
  `AcreditacionTipoDeSangre` BLOB NULL,
  `CertificadoDeEstudios` BLOB NOT NULL,
  `PadreRegistrado` VARCHAR(10) NOT NULL,
  `MadreRegistrado` VARCHAR(10) NOT NULL,
  `Telefono` VARCHAR(45) NOT NULL,
  `CorreoElectronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdAlumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionEscolar`.`MateriaAlumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`MateriaAlumno` (
  `Materia_IdMateria` INT NOT NULL,
  `Alumno_IdAlumno` INT NOT NULL,
  PRIMARY KEY (`Materia_IdMateria`, `Alumno_IdAlumno`),
  INDEX `fk_Materia_has_Alumno_Alumno1_idx` (`Alumno_IdAlumno` ASC) VISIBLE,
  INDEX `fk_Materia_has_Alumno_Materia1_idx` (`Materia_IdMateria` ASC) VISIBLE,
  CONSTRAINT `fk_Materia_has_Alumno_Materia1`
    FOREIGN KEY (`Materia_IdMateria`)
    REFERENCES `GestionEscolar`.`Materia` (`IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Alumno_Alumno1`
    FOREIGN KEY (`Alumno_IdAlumno`)
    REFERENCES `GestionEscolar`.`Alumno` (`IdAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionEscolar`.`Encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`Encargado` (
  `IdEncargado` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoPaterno` VARCHAR(45) NOT NULL,
  `ApellidoMaterno` VARCHAR(45) NOT NULL,
  `CURP` VARCHAR(45) NOT NULL,
  `LugarDeNacimiento` VARCHAR(45) NULL,
  `Escolaridad` VARCHAR(45) NOT NULL,
  `ServicioMedico` VARCHAR(45) NOT NULL,
  `Ocupacion` VARCHAR(45) NOT NULL,
  `DomicilioDeTrabajo` VARCHAR(45) NOT NULL,
  `TelefonoTrabajo` VARCHAR(45) NOT NULL,
  `TelefonoParticular` VARCHAR(45) NOT NULL,
  `EstadoCivil` VARCHAR(45) NOT NULL,
  `INE` BLOB NOT NULL,
  `CURPdoc` BLOB NOT NULL,
  `ComprobanteDomicilio` BLOB NOT NULL,
  `IngresoMensual` VARCHAR(45) NOT NULL,
  `NuevoFamiliar` VARCHAR(10) NOT NULL,
  `Parentesco` VARCHAR(45) NOT NULL,
  `CorreoElectronico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEncargado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionEscolar`.`EncargadoAlumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`EncargadoAlumno` (
  `Encargado_IdEncargado` INT NOT NULL,
  `Alumno_IdAlumno` INT NOT NULL,
  PRIMARY KEY (`Encargado_IdEncargado`, `Alumno_IdAlumno`),
  INDEX `fk_Encargado_has_Alumno_Alumno1_idx` (`Alumno_IdAlumno` ASC) VISIBLE,
  INDEX `fk_Encargado_has_Alumno_Encargado1_idx` (`Encargado_IdEncargado` ASC) VISIBLE,
  CONSTRAINT `fk_Encargado_has_Alumno_Encargado1`
    FOREIGN KEY (`Encargado_IdEncargado`)
    REFERENCES `GestionEscolar`.`Encargado` (`IdEncargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Encargado_has_Alumno_Alumno1`
    FOREIGN KEY (`Alumno_IdAlumno`)
    REFERENCES `GestionEscolar`.`Alumno` (`IdAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GestionEscolar`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GestionEscolar`.`Usuario` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `CorreoElectronico` VARCHAR(45) NOT NULL,
  `Contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
